"""
ingress_auctions.py
===================

This module provides the `IngressAuctions` class for managing
BNetzA auction data ingestion.

Features
--------
- Fetch live auctions
- Validate auction data
- Write/upsert auctions into a PostgreSQL database
- Rebuild the auctions table
"""

# Standard library
import asyncio
import datetime as dt
from typing import Any

# Third-party
import pandas as pd
import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_values

# Local packages
from omr_auctions import Auctions
from settings import settings


class IngressAuctions:
    """
    Manage ingestion of auction data from BNetzA into a PostgreSQL database.

    Responsibilities
    ----------------
    - Retrieve live auction data
    - Validate data integrity and types
    - Insert or update auctions in the database
    - Rebuild the auctions table with proper schema and indexes

    Attributes
    ----------
    :ivar TABLE_NAME: Name of the target database table ('auctions')
    :type TABLE_NAME: str
    :ivar _conn: Database connection object
    :type _conn: psycopg2.extensions.connection
    :ivar _auctions: Instance for retrieving live auction data
    :type _auctions: Auctions
    """

    TABLE_NAME: str = 'auctions'

    def __init__(self):
        self._conn = self._get_db_connection()
        self._auctions = Auctions()

    ################################################################
    # Public Methods
    ################################################################ 

    async def rebuild_table(self) -> None:
        """
        Drop and recreate the auctions table with its indexes.

        Steps performed
        ---------------
        - Drop the table if it exists
        - Create the table with the schema:
        - id: primary key, auto-increment
        - bidding_round: unique text
        - auction_name: non-null text
        - bid_submission_date: non-null date
        - announcement_date: date
        - effective_date: date
        - Create an index on bidding_round
        - Commit changes

        :raises Exception: If any SQL execution fails
        """

        sql_drop: sql.Composable = sql.SQL('''
            DROP TABLE IF EXISTS {table};
        ''').format(
            table=sql.Identifier(self.TABLE_NAME)
        )

        sql_create: sql.Composable= sql.SQL('''
            CREATE TABLE {table} (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                bidding_round TEXT UNIQUE,
                auction_name TEXT NOT NULL,
                bid_submission_date DATE NOT NULL,
                announcement_date DATE,
                effective_date DATE
            );
        ''').format(
            table=sql.Identifier(self.TABLE_NAME)
        )

        sql_indexes: sql.Composable = sql.SQL('''
            CREATE INDEX IF NOT EXISTS {idx} ON {tbl} ({col});
        ''').format(
            idx=sql.Identifier(f'{self.TABLE_NAME}_bidding_round_idx'),
            tbl=sql.Identifier(self.TABLE_NAME),
            col=sql.Identifier('bidding_round')
        )

        def run_query():
            cur = self._conn.cursor()

            try:
                cur.execute(sql_drop)
                cur.execute(sql_create)
                cur.execute(sql_indexes)
            except Exception as e:
                cur.close()
                self._conn.rollback()
                raise e
            
            cur.close()
            self._conn.commit()

        try:
            await asyncio.to_thread(run_query)
        except Exception as e:
            raise e
    
    async def start_ingress(self) -> dict[str, Any]:
        """
        Retrieve live auctions from BNetzA, normalize columns, 
        and insert into the database.

        Steps performed:
        - Fetch live auctions via self._auctions.get(live=True)
        - Rename columns to match database schema
        - Reset index
        - Write the DataFrame to the database

        :return: Dictionary with write statistics
        :rtype: dict[str, Any]
        :raises RuntimeError: If data retrieval or database write fails
        """

        try:
            df: pd.DataFrame = self._auctions.get(live=True)
        except Exception as e:
            raise RuntimeError(
                f'Auctions could not be retrieved from BNetzA. '
                f'Make sure the links are not broken.'
            )
        
        df = df.rename(columns={
            'auction': 'auction_name',
            'bid_submission_deadline': 'bid_submission_date'
        })

        df = df.reset_index()

        try:
            stats: dict[str, Any] = await self._write_to_db(df)
        except Exception as e:
            raise RuntimeError(
                f'Auction data could not be written to the database: {e}'
            )

        return stats

    ################################################################
    # Internal Methods - DB WRITE
    ################################################################
    
    def _validate_auctions_df(self, df: pd.DataFrame):
        """
        Validate a DataFrame before inserting into the ``auctions`` table.

        Checks performed:

        - Required columns exist: ``bidding_round``, ``auction_name``,
          ``bid_submission_date``, ``announcement_date``, ``effective_date``
        - No nulls in non-nullable columns
        - Correct dtypes:
            - ``bid_submission_date``: datetime
            - ``announcement_date``: datetime
            - ``effective_date``: datetime
        - ``bidding_round`` is unique

        :param df: DataFrame to validate
        :type df: pd.DataFrame
        :raises ValueError: If any validation fails
        """

        required_cols: list[str] = [
            'bidding_round', 'auction_name', 'bid_submission_date',
            'announcement_date', 'effective_date'
        ]

        non_nullable_columns: list[str] = [
            'bidding_round', 'auction_name', 'bid_submission_date'
        ]

        # 1. All required columns present
        missing: list[str] = [c for c in required_cols if c not in df.columns]
        if missing:
            raise ValueError(f'Missing required columns: {missing}')

        # 2. Non-nullable columns
        if df[non_nullable_columns].isnull().any().any():
            raise ValueError('Null values found in required columns')

        # 3. Correct types
        if not pd.api.types.is_datetime64_dtype(df['bid_submission_date']):
            raise ValueError(f'bid_submission_date must be a datetime column')
        
        if not pd.api.types.is_datetime64_dtype(df['announcement_date']):
            raise ValueError(f'announcement_date must be a datetime column')
        
        if not pd.api.types.is_datetime64_dtype(df['effective_date']):
            raise ValueError(f'effective_date must be a datetime column')
        
        # 4. Unique columns
        if not df['bidding_round'].is_unique:
            raise ValueError('Duplicate values found in bidding_round')
  
    async def _write_to_db(self, df: pd.DataFrame) -> dict[str, Any]:
        """
        Insert or update auctions into the `auctions` table.

        Workflow:

        1. Validate the DataFrame via ``_validate_df``
        2. Transform the DataFrame into a list of tuples for bulk insertion
        3. Execute an UPSERT query using ``execute_values``:
        - Inserts new rows
        - Updates ``auction_name``, ``bid_submission_date``, ``announcement_date``,
          and ``effective_date`` if a conflict occurs
        4. Returns statistics on inserted and updated rows, and elapsed time

        DataFrame schema:

        - ``bidding_round``: str, name of the bidding_round (e.g., SOL25-1)
        - ``auction_name``: str, name of the auction (e.g., EEG Solar)
        - ``bid_submission_date``: dt.datetime, date of the bid submission
        - ``announcement_date``: dt.datetime, date of the announcement
        - ``effective_date``: dt.datetime, date when the announcement becomes effective

        :param df: DataFrame with market prices to insert/update
        :type df: pd.DataFrame
        :return: Dictionary with number of inserts, updates, and elapsed time
        :rtype: dict[str, int | pd.Timedelta]
        """

        t: dt.datetime = pd.Timestamp.now()

        try:
            self._validate_auctions_df(df)
        except ValueError as e:
            raise e

        sql_insert: sql.Composable = sql.SQL('''
            INSERT INTO {table}
                (bidding_round, auction_name, bid_submission_date, announcement_date, effective_date)
            VALUES %s
            ON CONFLICT (bidding_round) DO UPDATE
            SET
                auction_name = EXCLUDED.auction_name,
                bid_submission_date = EXCLUDED.bid_submission_date,
                announcement_date = EXCLUDED.announcement_date,
                effective_date = EXCLUDED.effective_date
            RETURNING CASE WHEN xmax = 0 THEN 'insert' ELSE 'update' END AS action
        ''').format(
            table=sql.Identifier(self.TABLE_NAME)
        )

        nullable_dt_cols: list[str] = ['announcement_date', 'effective_date']
        df[nullable_dt_cols] = df[nullable_dt_cols].apply(lambda row: row.dt.date)
        df = df.where(pd.notnull(df), None)

        records: list[tuple] = [
            (
                row.bidding_round, row.auction_name, row.bid_submission_date,
                row.announcement_date, row.effective_date
            )
            for row in df.itertuples(index=False)
        ]

        def run_query():
            cur = self._conn.cursor()

            try:
                rows = execute_values(cur, sql_insert, records, fetch=True)
            except Exception as e:
                self._conn.rollback()
                raise e
            
            cur.close()
            self._conn.commit()
            return rows

        try:
            rows: list[tuple] = await asyncio.to_thread(run_query)
        except Exception as e:
            raise e

        stats: dict[str, Any] = {
            'inserts': sum(1 for r in rows if r[0] == 'insert'),
            'updates': sum(1 for r in rows if r[0] == 'update'),
            'time': pd.Timestamp.now() - t
        }

        return stats

    ################################################################
    # Internal Methods - DB Util
    ################################################################

    def _get_db_connection(self):
        """
        Create and return a new PostgreSQL database connection.

        :return: psycopg2 connection object
        :rtype: psycopg2.extensions.connection
        :raises psycopg2.OperationalError: If connection fails
        """
        
        conn = psycopg2.connect(settings.db.dsn)
    
        return conn
